substitutions:
  _TF_VERSION: '1.7.0'
  _PROJECT_ID: 'plated-analyzer-495108-v2'

steps:
  - name: 'alpine'
    id: 'Pobierz Terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        wget -q https://releases.hashicorp.com/terraform/${_TF_VERSION}/terraform_${_TF_VERSION}_linux_amd64.zip
        unzip -q terraform_${_TF_VERSION}_linux_amd64.zip
        mv terraform /workspace/terraform

  - name: 'alpine'
    id: 'CI - terraform fmt check'
    entrypoint: '/workspace/terraform'
    args: [fmt, -check, -recursive]

  - name: 'alpine'
    id: 'CI - terraform validate'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        /workspace/terraform init -backend=false
        /workspace/terraform validate
    env:
      - 'TF_VAR_project_id=${_PROJECT_ID}'

  - name: 'alpine'
    id: 'CI - terraform plan (preview only)'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        /workspace/terraform init \
          -backend-config=bucket=tfstate-${_PROJECT_ID} \
          -backend-config=prefix=gke/terraform.tfstate
        /workspace/terraform plan
    env:
      - 'TF_VAR_project_id=${_PROJECT_ID}'

options:
  logging: CLOUD_LOGGING_ONLY
